### PR TITLE
Feature008/navigation

### PR DESCRIPTION
**Pull request by acerasoni**

### CODE REVIEW

**Review by al-exisar — DISMISSED** [review]

**Review by confiscar — DISMISSED** [review]
Hey thats pretty good! Keep it up!

**Comment by ka5p3rr** [comment]
Sonar doesn't like this, do we still want to merge?

**Comment by ka5p3rr** [comment]
> Sonar doesn't like this, do we still want to merge?

Issues has been fixed. We can proceed.

**Review by ka5p3rr — DISMISSED** [review]
Good to go now.

**Review by ka5p3rr — APPROVED** [review]

**Review by confiscar — APPROVED** [review]
Looks good

**Pull request merged**
