### PR TITLE
Implementing health functionality

### PR DESCRIPTION
**Pull request by al-exisar**

### CODE REVIEW

**Review by acerasoni — DISMISSED** [review]

**Review by confiscar — DISMISSED** [review]
Good work

**Review by acerasoni — DISMISSED** [review]

**Review by confiscar — DISMISSED** [review]
Good

**Review by acerasoni — APPROVED** [review]

**Review by acerasoni — DISMISSED** [review]

**Review by confiscar — DISMISSED** [review]
third times the charge

**Review by aidanreed — CHANGES_REQUESTED** [review]
Not complete game resets when space bar is pressed

**Comment by ka5p3rr** [comment]
closing PR, resolved on another branch

**Pull request closed without merging**
